os: linux
dist: trusty
language:
  - cpp
  - python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - python setup.py --quiet install
compiler: gcc
sudo: required
group: deprecated-2017Q2
before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get update -qq
  - sudo apt-get install g++ -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtscript5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev libboost-all-dev
script:
  - nosetests
  - ./test.bash
  - ./configure --enable-gcov && make && make check
  - export QT_SELECT=qt5
  - qmake CONFIG+=debug -o Makefile build.pro;
  - make -j $(nproc)
  - ./bin/MavenTests -xml
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
